import { Elms_Sans } from 'next/font/google';
import "./globals.css";
import "@mantine/core/styles.css";
import { createTheme, MantineProvider } from "@mantine/core";

import Navbar from "@/components/Navbar";
import Footer from "@/components/common/Footer.js";

const elmsSans = Elms_Sans({
  subsets: ['latin'],
  display: 'swap',
});

// TODO: Change this!!!
export const metadata = {
  title: "Por falar nisso",
  description: "Generated by create next app",
};

const theme = createTheme({
  colors: {
    "my-orange": [
      "#744310",
      "#93513a",
      "#b06347",
      "#ce7554",
      "#ed8762",
      "#f09472",
      "#f3a082",
      "#f6ac92",
      "#f6ac92",
      "#fac4b1",
    ],
    "font-white": Array(10).fill("#fffbf5"),
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={elmsSans.className}>
        <MantineProvider theme={theme}>
          <Navbar />

          {children}
        <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
